kind: Service
apiVersion: v1
metadata:
  name: chai-app-service
  namespace: chai-app
spec:
  selector:
    apps: chai-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP
