kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: apache
  template:
    metadata:
      labels:
        apps: apache
    spec:
      containers:
        - name: apache
          image: httpd:alpine3.22
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 125Mi
            limits:
              cpu: 200m
              memory: 256Mi
